"""knowledge_base

Revision ID: 4d19bec6d86b
Revises: 43a9dc955b00
Create Date: 2026-09-17 10:39:17.109780+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.types

revision: str = "4d19bec6d86b"
down_revision: str | None = "43a9dc955b00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    # Defensive: docker/postgres-init/01-extensions.sql already does this on
    # first cluster init, but that script only runs against an empty data
    # dir — a migration against an existing external Postgres needs this too.
    if _is_postgres():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("file", "url", "text", name="data_source_type", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "error",
                name="data_source_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_data_sources_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    op.create_index(
        op.f("ix_data_sources_assistant_id"), "data_sources", ["assistant_id"], unique=False
    )
    op.create_index(op.f("ix_data_sources_org_id"), "data_sources", ["org_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("mime", sa.String(length=120), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_documents_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_documents_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_documents_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_assistant_id"), "documents", ["assistant_id"], unique=False)
    op.create_index(
        op.f("ix_documents_data_source_id"), "documents", ["data_source_id"], unique=False
    )
    op.create_index(op.f("ix_documents_org_id"), "documents", ["org_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("context_prefix", sa.Text(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("embedding", app.db.types.Embedding(dim=1024), nullable=True),
        sa.Column(
            "tsv", sa.Text().with_variant(postgresql.TSVECTOR(), "postgresql"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_chunks_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_chunks_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    op.create_index(op.f("ix_chunks_assistant_id"), "chunks", ["assistant_id"], unique=False)
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_chunks_org_id"), "chunks", ["org_id"], unique=False)
    # ### end Alembic commands ###

    # Postgres-only: neither index type nor the vector/tsvector columns
    # behind them exist on SQLite (see app/db/types.py — both degrade to
    # plain text there for offline model tests only).
    if _is_postgres():
        op.execute(
            "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )
        op.execute("CREATE INDEX ix_chunks_tsv_gin ON chunks USING gin (tsv)")


def downgrade() -> None:
    if _is_postgres():
        op.execute("DROP INDEX IF EXISTS ix_chunks_tsv_gin")
        op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_org_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_assistant_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_documents_org_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_data_source_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_assistant_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_data_sources_org_id"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_assistant_id"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
