"""budgets

Task 5.7. Spend caps for an org or one assistant, per UTC day or month.
Only the limit is stored; spend is summed from `usage_events` for the
current period, so two composite indexes make that sum cheap.

Revision ID: 6f0fd4064993
Revises: c9331dc49c69"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6f0fd4064993"
down_revision: str | None = "c9331dc49c69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("assistant_id", sa.Uuid(), nullable=True),
        sa.Column("scope_key", sa.String(length=40), nullable=False),
        sa.Column(
            "period",
            sa.Enum("day", "month", name="budget_period", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("limit_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_budgets_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_budgets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_budgets_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint("org_id", "scope_key", "period", name="uq_budget_scope_period"),
    )
    op.create_index(op.f("ix_budgets_assistant_id"), "budgets", ["assistant_id"], unique=False)
    op.create_index(op.f("ix_budgets_org_id"), "budgets", ["org_id"], unique=False)
    op.create_index(
        "ix_usage_events_assistant_created",
        "usage_events",
        ["assistant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_events_org_created", "usage_events", ["org_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_events_org_created", table_name="usage_events")
    op.drop_index("ix_usage_events_assistant_created", table_name="usage_events")
    op.drop_index(op.f("ix_budgets_org_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_assistant_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
