"""db integrations and approvals

Revision ID: 72f2c204f174
Revises: 7c2f4a91be30
Create Date: 2026-09-21 08:38:34.955756+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "72f2c204f174"
down_revision: str | None = "7c2f4a91be30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "db_password",
                "mcp_headers",
                "api_key",
                name="secret_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("dek_wrapped", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_secrets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secrets")),
    )
    op.create_index(op.f("ix_secrets_org_id"), "secrets", ["org_id"], unique=False)
    op.create_table(
        "db_connections",
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "engine",
            sa.Enum(
                "postgres",
                "mysql",
                "sqlite",
                "mongodb",
                name="db_engine",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("database", sa.String(length=500), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("secret_ref", sa.Uuid(), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "ssl",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "unknown", "ok", "error", name="db_connection_status", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_db_connections_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_db_connections_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_ref"],
            ["secrets.id"],
            name=op.f("fk_db_connections_secret_ref_secrets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_db_connections")),
    )
    op.create_index(
        op.f("ix_db_connections_assistant_id"), "db_connections", ["assistant_id"], unique=False
    )
    op.create_index(op.f("ix_db_connections_org_id"), "db_connections", ["org_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.Column(
            "input",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "risk",
            sa.Enum("low", "medium", "high", name="approval_risk", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "expired",
                name="approval_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_approvals_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_approvals_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        op.f("ix_approvals_conversation_id"), "approvals", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_approvals_org_id"), "approvals", ["org_id"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_table(
        "db_schema_cache",
        sa.Column("db_connection_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column(
            "schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "refreshed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["db_connection_id"],
            ["db_connections.id"],
            name=op.f("fk_db_schema_cache_db_connection_id_db_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_db_schema_cache_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_db_schema_cache")),
        sa.UniqueConstraint("db_connection_id", name="uq_db_schema_cache_connection"),
    )
    op.create_index(
        op.f("ix_db_schema_cache_db_connection_id"),
        "db_schema_cache",
        ["db_connection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_db_schema_cache_org_id"), "db_schema_cache", ["org_id"], unique=False)
    # NOTE: autogenerate wanted to drop `ix_chunks_embedding_hnsw` and
    # `ix_chunks_tsv_gin` here. They are created with raw SQL in migration
    # 4d19bec6d86b (Alembic cannot reflect an HNSW/GIN opclass index), so it
    # sees them as "not in the models" and proposes a drop. Dropping them would
    # silently turn every vector search into a sequential scan. Left alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (see upgrade: those indexes were never dropped, so nothing to recreate)
    op.drop_index(op.f("ix_db_schema_cache_org_id"), table_name="db_schema_cache")
    op.drop_index(op.f("ix_db_schema_cache_db_connection_id"), table_name="db_schema_cache")
    op.drop_table("db_schema_cache")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_org_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_conversation_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_db_connections_org_id"), table_name="db_connections")
    op.drop_index(op.f("ix_db_connections_assistant_id"), table_name="db_connections")
    op.drop_table("db_connections")
    op.drop_index(op.f("ix_secrets_org_id"), table_name="secrets")
    op.drop_table("secrets")
    # ### end Alembic commands ###
