"""runs route

Task 5.10. How the router sorted the message ("simple", "normal", "hard"),
when a router node is wired in; `runs.effort` is what the turn ran at.

Revision ID: d14dacedc92a
Revises: 6f0fd4064993"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "d14dacedc92a"
down_revision: str | None = "6f0fd4064993"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("route", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "route")
    # ### end Alembic commands ###
